Repository TEAM-YOAJUNG/backend-server, pull requests merged in 2024-11, with the labels that each got.

#49 [FEAT] 프로필 이미지 관련 기능 추가
  user-service/.gitattributes
  user-service/.gitignore
  user-service/build.gradle
  user-service/gradle/wrapper/gradle-wrapper.jar
  user-service/gradle/wrapper/gradle-wrapper.properties
  user-service/gradlew
  user-service/gradlew.bat
  user-service/settings.gradle
  user-service/src/main/java/club/gach_dong/UserApplication.java
  user-service/src/main/java/club/gach_dong/api/UserApiSpecification.java
  user-service/src/main/java/club/gach_dong/config/GcpStorageConfig.java
  user-service/src/main/java/club/gach_dong/config/SwaggerConfig.java
  user-service/src/main/java/club/gach_dong/controller/UserController.java
  user-service/src/main/java/club/gach_dong/dto/request/UserProfileRequest.java
  user-service/src/main/java/club/gach_dong/dto/response/UserProfileResponse.java
  user-service/src/main/java/club/gach_dong/entity/User.java
  user-service/src/main/java/club/gach_dong/exception/CustomException.java
  user-service/src/main/java/club/gach_dong/exception/ErrorStatus.java
  user-service/src/main/java/club/gach_dong/exception/SuccessStatus.java
  user-service/src/main/java/club/gach_dong/repository/UserRepository.java
  user-service/src/main/java/club/gach_dong/service/UserService.java
  user-service/src/main/resources/application-dev.yaml
  user-service/src/main/resources/application.yaml
  user-service/src/test/java/club/gach_dong/GachDongApplicationTests.java
Labels: feature

#53 [Fix] auth-service URI PATH 변경
  auth-service/src/main/java/club/gach_dong/api/AuthApiSpecification.java
  auth-service/src/main/java/club/gach_dong/api/PublicAuthApiSpecification.java
Labels: fix

#54 [FEAT] 지원서 양식 및 지원 관련 기능 인증/인가 처리 추가
  application-service/src/main/java/club/gach_dong/api/ApplicationApiSpecification.java
  application-service/src/main/java/club/gach_dong/controller/ApplicationController.java
  application-service/src/main/java/club/gach_dong/domain/Application.java
  application-service/src/main/java/club/gach_dong/dto/request/ApplicationRequestDTO.java
  application-service/src/main/java/club/gach_dong/gcp/ObjectStorageService.java
  application-service/src/main/java/club/gach_dong/gcp/ObjectStorageServiceConfig.java
  application-service/src/main/java/club/gach_dong/repository/ApplicationRepository.java
  application-service/src/main/java/club/gach_dong/response/status/ErrorStatus.java
  application-service/src/main/java/club/gach_dong/response/status/InSuccess.java
  application-service/src/main/java/club/gach_dong/restClient/HeaderInterceptor.java
  application-service/src/main/java/club/gach_dong/restClient/RestClientConfig.java
  application-service/src/main/java/club/gach_dong/service/ApplicationService.java
  application-service/src/main/java/club/gach_dong/service/AuthorizationService.java
  application-service/src/main/resources/application.yml
Labels: feature

#57 [FEAT] 동아리 서비스에서 모집 공고 조회 API 구현
  api-gateway/build.gradle
  club-service/src/main/java/club/gach_dong/api/ClubPublicApiSpecification.java
  club-service/src/main/java/club/gach_dong/controller/ClubPublicController.java
  club-service/src/main/java/club/gach_dong/domain/BaseEntity.java
  club-service/src/main/java/club/gach_dong/domain/Club.java
  club-service/src/main/java/club/gach_dong/domain/Recruitment.java
  club-service/src/main/java/club/gach_dong/dto/response/ClubRecruitmentDetailResponse.java
  club-service/src/main/java/club/gach_dong/dto/response/ClubRecruitmentResponse.java
  club-service/src/main/java/club/gach_dong/repository/ClubRepository.java
  club-service/src/main/java/club/gach_dong/service/ClubService.java
  club-service/src/main/java/club/gach_dong/service/ClubServiceImpl.java
  club-service/src/test/java/club/gach_dong/domain/RecruitmentTest.java
Labels: feature

#61 [feat] Application Domain DTO 수정 및 지원일 추가
  application-service/src/main/java/club/gach_dong/domain/Application.java
  application-service/src/main/java/club/gach_dong/domain/ApplicationForm.java
  application-service/src/main/java/club/gach_dong/dto/request/ApplicationRequestDTO.java
  application-service/src/main/java/club/gach_dong/dto/response/ApplicationResponseDTO.java
  application-service/src/main/java/club/gach_dong/service/ApplicationService.java
Labels: feature

#58 [FEAT] 공통 예외 처리 로직 구현
  club-service/src/main/java/club/gach_dong/config/GlobalExceptionHandler.java
  club-service/src/main/java/club/gach_dong/dto/response/ArrayResponse.java
  club-service/src/main/java/club/gach_dong/dto/response/ErrorResponse.java
  club-service/src/main/java/club/gach_dong/exception/ClubException.java
  club-service/src/main/java/club/gach_dong/exception/DomainException.java
  club-service/src/main/java/club/gach_dong/exception/ErrorCode.java
  club-service/src/main/java/club/gach_dong/exception/RedirectUriNotFoundException.java
  club-service/src/main/java/club/gach_dong/service/ClubServiceImpl.java
Labels: feature

#69 [FEAT] ADMIN 동아리 서비스 - 생성 API 구현 (동아리, 활동 내용, 연락처 정보)
  api-gateway/src/main/java/club/gach_dong/filter/JWTAuthenticationFilter.java
  club-service/src/main/java/club/gach_dong/annotation/RequestUserReferenceId.java
  club-service/src/main/java/club/gach_dong/api/ClubAdminApiSpecification.java
  club-service/src/main/java/club/gach_dong/api/ClubApiSpecification.java
  club-service/src/main/java/club/gach_dong/api/ClubPublicApiSpecification.java
  club-service/src/main/java/club/gach_dong/config/UserReferenceIdParameterResolver.java
  club-service/src/main/java/club/gach_dong/config/WebConfig.java
  club-service/src/main/java/club/gach_dong/controller/ClubAdminController.java
  club-service/src/main/java/club/gach_dong/controller/ClubController.java
  club-service/src/main/java/club/gach_dong/controller/ClubPublicController.java
  club-service/src/main/java/club/gach_dong/dto/request/CreateClubActivityRequest.java
  club-service/src/main/java/club/gach_dong/dto/request/CreateClubContactInfoRequest.java
  club-service/src/main/java/club/gach_dong/dto/request/CreateClubRecruitmentRequest.java
  club-service/src/main/java/club/gach_dong/dto/response/CreateClubActivityResponse.java
  club-service/src/main/java/club/gach_dong/dto/response/CreateClubContactInfoResponse.java
  club-service/src/main/java/club/gach_dong/dto/response/CreateClubRecruitmentResponse.java
  club-service/src/main/java/club/gach_dong/dto/response/CreateClubResponse.java
  club-service/src/main/java/club/gach_dong/service/ClubService.java
  club-service/src/main/java/club/gach_dong/service/ClubServiceImpl.java
Labels: feature

#68 [Fix] user-service의 userId 필드 수정
  user-service/src/main/java/club/gach_dong/annotation/RequestUserReferenceId.java
  user-service/src/main/java/club/gach_dong/api/UserApiSpecification.java
  user-service/src/main/java/club/gach_dong/config/UserReferenceIdParameterResolver.java
  user-service/src/main/java/club/gach_dong/config/WebConfig.java
  user-service/src/main/java/club/gach_dong/controller/UserController.java
  user-service/src/main/java/club/gach_dong/dto/response/UserProfileResponse.java
  user-service/src/main/java/club/gach_dong/entity/User.java
  user-service/src/main/java/club/gach_dong/repository/UserRepository.java
  user-service/src/main/java/club/gach_dong/service/UserService.java
Labels: chore

#73 [FEAT] Add Swagger Authorization Config
  application-service/src/main/java/club/gach_dong/config/SwaggerConfig.java
Labels: feature

#77 [FIX] user-service REFERENCE_ID_HEADER_KEY 값 수정 및 controller mapping 삭제
  user-service/src/main/java/club/gach_dong/config/UserReferenceIdParameterResolver.java
  user-service/src/main/java/club/gach_dong/controller/UserController.java
Labels: fix

#79 [FIX] Application Domain, User와 Admin용 API 분리
  application-service/src/main/java/club/gach_dong/api/ApplicationAdminApiSpecification.java
  application-service/src/main/java/club/gach_dong/api/ApplicationApiSpecification.java
  application-service/src/main/java/club/gach_dong/controller/ApplicationAdminController.java
  application-service/src/main/java/club/gach_dong/controller/ApplicationController.java
  application-service/src/main/java/club/gach_dong/service/ApplicationService.java
  application-service/src/main/java/club/gach_dong/service/AuthorizationService.java
Labels: fix

#82 [FEAT] auth-service 회원가입용 인증 코드 발송 api 추가
  auth-service/src/main/java/club/gach_dong/api/PublicAdminAuthApiSpecification.java
  auth-service/src/main/java/club/gach_dong/api/PublicAuthApiSpecification.java
  auth-service/src/main/java/club/gach_dong/controller/PublicAdminAuthController.java
  auth-service/src/main/java/club/gach_dong/controller/PublicAuthController.java
  auth-service/src/main/java/club/gach_dong/service/AdminService.java
  auth-service/src/main/java/club/gach_dong/service/UserService.java
Labels: feature

#85 [FIX] user-service gcpStorageConfig 수정
  user-service/src/main/java/club/gach_dong/config/GcpStorageConfig.java
Labels: fix

#92 [FIX] Application Domain 공통 Exception Handler / Header 추출 적용
  application-service/src/main/java/club/gach_dong/annotation/RequestUserReferenceId.java
  application-service/src/main/java/club/gach_dong/api/ApplicationAdminApiSpecification.java
  application-service/src/main/java/club/gach_dong/api/ApplicationApiSpecification.java
  application-service/src/main/java/club/gach_dong/config/GlobalExceptionHandler.java
  application-service/src/main/java/club/gach_dong/config/UserReferenceIdParameterResolver.java
  application-service/src/main/java/club/gach_dong/config/WebConfig.java
  application-service/src/main/java/club/gach_dong/controller/ApplicationAdminController.java
  application-service/src/main/java/club/gach_dong/controller/ApplicationController.java
  application-service/src/main/java/club/gach_dong/exception/ApplicationException.java
  application-service/src/main/java/club/gach_dong/exception/ClubException.java
  application-service/src/main/java/club/gach_dong/exception/CustomException.java
  application-service/src/main/java/club/gach_dong/exception/DomainException.java
  application-service/src/main/java/club/gach_dong/exception/FileException.java
  application-service/src/main/java/club/gach_dong/exception/GlobalExceptionHandler.java
  application-service/src/main/java/club/gach_dong/exception/RedirectUriNotFoundException.java
  application-service/src/main/java/club/gach_dong/exception/UserException.java
  application-service/src/main/java/club/gach_dong/gcp/ObjectStorageService.java
  application-service/src/main/java/club/gach_dong/response/ErrorDTO.java
  application-service/src/main/java/club/gach_dong/response/ErrorResponse.java
  application-service/src/main/java/club/gach_dong/response/ResForm.java
  application-service/src/main/java/club/gach_dong/response/ResponseDTO.java
  application-service/src/main/java/club/gach_dong/response/status/ErrorCode.java
  application-service/src/main/java/club/gach_dong/response/status/ErrorStatus.java
  application-service/src/main/java/club/gach_dong/service/ApplicationService.java
  application-service/src/main/java/club/gach_dong/service/AuthorizationService.java
  application-service/src/main/java/club/gach_dong/service/FileService.java
Labels: fix

#93 [FEAT] club과의 통신 기능 추가
  application-service/src/main/java/club/gach_dong/config/UserReferenceIdParameterResolver.java
  application-service/src/main/java/club/gach_dong/controller/MockUpController.java
  application-service/src/main/java/club/gach_dong/exception/ClubException.java
  application-service/src/main/java/club/gach_dong/response/status/ErrorCode.java
  application-service/src/main/java/club/gach_dong/service/ApplicationService.java
  application-service/src/main/java/club/gach_dong/service/AuthorizationService.java
  application-service/src/main/resources/application-dev.yaml
  application-service/src/main/resources/application.yaml
Labels: feature

#102 [FEAT] 임시 저장 상태인 지원 내역에 대하여 조회하는 API
  application-service/src/main/java/club/gach_dong/api/ApplicationApiSpecification.java
  application-service/src/main/java/club/gach_dong/controller/ApplicationController.java
  application-service/src/main/java/club/gach_dong/dto/response/ApplicationResponseDTO.java
  application-service/src/main/java/club/gach_dong/repository/ApplicationRepository.java
  application-service/src/main/java/club/gach_dong/response/status/InSuccess.java
  application-service/src/main/java/club/gach_dong/service/ApplicationService.java
Labels: feature

#101 [FEAT] user-service와의 통신으로 프로필 이미지 조회 api에 profileImageUrl 추가
  auth-service/src/main/java/club/gach_dong/config/RestTemplateConfig.java
  auth-service/src/main/java/club/gach_dong/controller/AdminAuthController.java
  auth-service/src/main/java/club/gach_dong/controller/AuthController.java
  auth-service/src/main/java/club/gach_dong/dto/response/UserProfileResponse.java
  auth-service/src/main/java/club/gach_dong/entity/Admin.java
  auth-service/src/main/java/club/gach_dong/entity/User.java
  auth-service/src/main/java/club/gach_dong/repository/AdminRepository.java
  auth-service/src/main/java/club/gach_dong/repository/UserRepository.java
  auth-service/src/main/java/club/gach_dong/service/AdminService.java
  auth-service/src/main/java/club/gach_dong/service/UserService.java
  auth-service/src/main/java/club/gach_dong/util/JwtUtil.java
  auth-service/src/main/resources/application.yaml
Labels: feature

#111 [FEAT] auth-service의 refresh token 추가 및 다수의 사용자 프로필 조회 api 추가
  auth-service/src/main/java/club/gach_dong/api/AdminAuthApiSpecification.java
  auth-service/src/main/java/club/gach_dong/api/AuthApiSpecification.java
  auth-service/src/main/java/club/gach_dong/api/PublicAuthApiSpecification.java
  auth-service/src/main/java/club/gach_dong/controller/AdminAuthController.java
  auth-service/src/main/java/club/gach_dong/controller/AuthController.java
  auth-service/src/main/java/club/gach_dong/controller/PublicAdminAuthController.java
  auth-service/src/main/java/club/gach_dong/controller/PublicAuthController.java
  auth-service/src/main/java/club/gach_dong/dto/request/ProfilesRequest.java
  auth-service/src/main/java/club/gach_dong/dto/response/AuthResponse.java
  auth-service/src/main/java/club/gach_dong/dto/response/TokenResponse.java
  auth-service/src/main/java/club/gach_dong/dto/response/UserProfileResponse.java
  auth-service/src/main/java/club/gach_dong/entity/Admin.java
  auth-service/src/main/java/club/gach_dong/entity/User.java
  auth-service/src/main/java/club/gach_dong/service/AdminService.java
  auth-service/src/main/java/club/gach_dong/service/UserService.java
  auth-service/src/main/java/club/gach_dong/util/JwtUtil.java
Labels: feature

#115 [FEAT] 요구사항을 위한 동아리 서비스 API 구현 v3
  club-service/src/main/java/club/gach_dong/api/ClubAdminApiSpecification.java
  club-service/src/main/java/club/gach_dong/controller/ClubAdminController.java
  club-service/src/main/java/club/gach_dong/dto/response/CreateClubContactInfoResponse.java
  club-service/src/main/java/club/gach_dong/dto/response/CreateClubRecruitmentResponse.java
  club-service/src/main/java/club/gach_dong/service/ClubService.java
  club-service/src/main/java/club/gach_dong/service/ClubServiceImpl.java
Labels: feature

#117 [FIX] user-service X-USER-REFERENCE-ID 오타 수정
  user-service/src/main/java/club/gach_dong/config/UserReferenceIdParameterResolver.java
Labels: fix

#120 [FEAT] applicationId로 지원 내역 단건 조회하는 API 추가
  application-service/src/main/java/club/gach_dong/api/ApplicationAdminApiSpecification.java
  application-service/src/main/java/club/gach_dong/controller/ApplicationAdminController.java
  application-service/src/main/java/club/gach_dong/response/status/InSuccess.java
  application-service/src/main/java/club/gach_dong/service/ApplicationService.java
Labels: feature

#121 [FEAT] admin-service 초대코드 발행, 등록 api 추가
  admin-service/.gitattributes
  admin-service/.gitignore
  admin-service/build.gradle
  admin-service/gradle/wrapper/gradle-wrapper.jar
  admin-service/gradle/wrapper/gradle-wrapper.properties
  admin-service/gradlew
  admin-service/gradlew.bat
  admin-service/settings.gradle
  admin-service/src/main/java/club/gach_dong/AdminApplication.java
  admin-service/src/main/java/club/gach_dong/annotation/RequestUserReferenceId.java
  admin-service/src/main/java/club/gach_dong/api/AdminApiSpecification.java
  admin-service/src/main/java/club/gach_dong/config/RestTemplateConfig.java
  admin-service/src/main/java/club/gach_dong/config/SwaggerConfig.java
  admin-service/src/main/java/club/gach_dong/config/UserReferenceIdParameterResolver.java
  admin-service/src/main/java/club/gach_dong/config/WebConfig.java
  admin-service/src/main/java/club/gach_dong/controller/AdminController.java
  admin-service/src/main/java/club/gach_dong/dto/request/InviteCodeRequest.java
  admin-service/src/main/java/club/gach_dong/dto/response/InviteCodeRegisterResponse.java
  admin-service/src/main/java/club/gach_dong/dto/response/InviteCodeResponse.java
  admin-service/src/main/java/club/gach_dong/entity/Admin.java
  admin-service/src/main/java/club/gach_dong/entity/InviteCode.java
  admin-service/src/main/java/club/gach_dong/exception/DomainException.java
  admin-service/src/main/java/club/gach_dong/exception/ErrorStatus.java
  admin-service/src/main/java/club/gach_dong/exception/UserException.java
  admin-service/src/main/java/club/gach_dong/repository/AdminRepository.java
  admin-service/src/main/java/club/gach_dong/repository/InviteCodeRepository.java
  admin-service/src/main/java/club/gach_dong/response/ErrorResponse.java
  admin-service/src/main/java/club/gach_dong/response/status/ErrorCode.java
  admin-service/src/main/java/club/gach_dong/service/AdminService.java
  admin-service/src/main/resources/application-dev.yaml
  admin-service/src/main/resources/application.yaml
  admin-service/src/test/java/club/gach_dong/GachDongApplicationTests.java
Labels: feature

#124 [FIX] admin-service package명 오타 수정
  admin-service/src/main/java/club/gach_dong/config/UserReferenceIdParameterResolver.java
  admin-service/src/main/java/club/gach_dong/response/ErrorResponse.java
Labels: fix

#125 [FIX] user-service userApiSpec에서 @SecurityRequirement 누락 수정
  user-service/src/main/java/club/gach_dong/api/UserApiSpecification.java
Labels: fix

#128 [FIX] admin-service의 club-serivce와의 통신 URL 수정
  admin-service/src/main/java/club/gach_dong/api/AdminApiSpecification.java
  admin-service/src/main/java/club/gach_dong/dto/request/AuthorizeAdminRequest.java
  admin-service/src/main/java/club/gach_dong/dto/request/InviteCodeRequest.java
  admin-service/src/main/java/club/gach_dong/service/AdminService.java
Labels: fix

#132 [REFACTOR] Application Domain Refactoring v1
  application-service/src/main/java/club/gach_dong/api/ApplicationAdminApiSpecification.java
  application-service/src/main/java/club/gach_dong/api/ApplicationApiSpecification.java
  application-service/src/main/java/club/gach_dong/controller/ApplicationAdminController.java
  application-service/src/main/java/club/gach_dong/controller/ApplicationController.java
  application-service/src/main/java/club/gach_dong/controller/MockUpController.java
  application-service/src/main/java/club/gach_dong/domain/Application.java
  application-service/src/main/java/club/gach_dong/domain/ApplicationForm.java
  application-service/src/main/java/club/gach_dong/dto/request/ApplicationRequestDTO.java
  application-service/src/main/java/club/gach_dong/dto/response/ApplicationResponseDTO.java
  application-service/src/main/java/club/gach_dong/repository/ApplicationRepository.java
  application-service/src/main/java/club/gach_dong/response/ResForm.java
  application-service/src/main/java/club/gach_dong/service/ApplicationService.java
Labels: refactor

#136 [FEAT] auth-service 사용자 이름 변경 api 추가
  auth-service/src/main/java/club/gach_dong/api/AdminAuthApiSpecification.java
  auth-service/src/main/java/club/gach_dong/api/AuthApiSpecification.java
  auth-service/src/main/java/club/gach_dong/controller/AdminAuthController.java
  auth-service/src/main/java/club/gach_dong/controller/AuthController.java
  auth-service/src/main/java/club/gach_dong/dto/response/ChangeNameResponse.java
  auth-service/src/main/java/club/gach_dong/service/AdminService.java
  auth-service/src/main/java/club/gach_dong/service/UserService.java
Labels: feature

#139 [FEAT] application Table에서 clubName을 clubId로 대체
  application-service/src/main/java/club/gach_dong/domain/Application.java
  application-service/src/main/java/club/gach_dong/dto/request/ApplicationRequestDTO.java
  application-service/src/main/java/club/gach_dong/dto/response/ApplicationResponseDTO.java
  application-service/src/main/java/club/gach_dong/service/ApplicationService.java
Labels: feature

#140 [FIX] auth-service에서 refresh-token 관리 방법 수정 및 access-token 재발급 api 수정
  auth-service/src/main/java/club/gach_dong/api/AdminAuthApiSpecification.java
  auth-service/src/main/java/club/gach_dong/api/AuthApiSpecification.java
  auth-service/src/main/java/club/gach_dong/controller/AdminAuthController.java
  auth-service/src/main/java/club/gach_dong/controller/AuthController.java
  auth-service/src/main/java/club/gach_dong/dto/response/TokenResponse.java
  auth-service/src/main/java/club/gach_dong/util/JwtUtil.java
Labels: fix

#145 [FEAT] Club Domain FE 요구사항 반영
  club-service/src/main/java/club/gach_dong/api/ClubPublicApiSpecification.java
  club-service/src/main/java/club/gach_dong/controller/ClubPublicController.java
  club-service/src/main/java/club/gach_dong/domain/Club.java
  club-service/src/main/java/club/gach_dong/domain/Recruitment.java
  club-service/src/main/java/club/gach_dong/domain/RecruitmentStatus.java
  club-service/src/main/java/club/gach_dong/dto/response/ClubRecruitmentDetailResponse.java
  club-service/src/main/java/club/gach_dong/dto/response/ClubRecruitmentResponse.java
  club-service/src/main/java/club/gach_dong/service/ClubReadService.java
  club-service/src/main/java/club/gach_dong/service/ClubService.java
Labels: feature

#146 [FIX] Application Domain 지원 API Status 관련 Logic 수정
  application-service/src/main/java/club/gach_dong/dto/response/ClubResponseDTO.java
  application-service/src/main/java/club/gach_dong/exception/ClubException.java
  application-service/src/main/java/club/gach_dong/repository/ApplicationRepository.java
  application-service/src/main/java/club/gach_dong/response/status/ErrorCode.java
  application-service/src/main/java/club/gach_dong/service/ApplicationService.java
  application-service/src/main/java/club/gach_dong/service/ServiceMeshService.java
  application-service/src/main/resources/application.yaml
Labels: fix

#150 [HOTFIX] applicationStatus 부분 수정
  application-service/src/main/java/club/gach_dong/service/ApplicationService.java
Labels: fix

#152 [FIX] admin-service의 club-service 요청 본문 수정
  admin-service/src/main/java/club/gach_dong/service/AdminService.java
Labels: fix

#153 [FIX] admin-service의 club-service api 호출 시 ResponseEntity 수정
  admin-service/src/main/java/club/gach_dong/service/AdminService.java
Labels: fix
